-- UKIE AI BRIDGE durable ledger foundation
-- Applied to Supabase project vbuokbwglauibabinaqs on 2026-09-10.
-- No secrets are stored here. RLS must remain enabled on all exposed tables.

create table if not exists public.ukie_bridge_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_key text not null unique,
  device_name text not null,
  platform text not null default 'windows',
  status text not null default 'UNKNOWN' check (status in ('UNKNOWN','OFFLINE','ONLINE','BUSY','WAIT_RESOURCE','ERROR')),
  bridge_version text,
  protocol_version text not null default 'ukie_job_v1',
  os_info jsonb not null default '{}'::jsonb,
  hardware_info jsonb not null default '{}'::jsonb,
  blender_info jsonb not null default '{}'::jsonb,
  capabilities jsonb not null default '[]'::jsonb,
  drive_root_id text,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ukie_bridge_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  job_key text not null unique,
  device_id uuid references public.ukie_bridge_devices(id) on delete set null,
  action text not null check (action in ('device_status','analyze_blend','upload_results')),
  project text not null check (project in ('BP3D','CSMC','BRIDGE_TEST')),
  status text not null default 'QUEUED' check (status in ('QUEUED','CLAIMED','INPUT_DOWNLOADING','INPUT_VERIFIED','WORKING_COPY_CREATED','PREFLIGHT','BLENDER_RUNNING','LOCAL_SAVED','HASHED','UPLOADING','UPLOADED','READBACK_VERIFYING','VERIFIED','COMPLETED','FAILED','TIMEOUT','INTERRUPTED','WAIT_RESOURCE','NEEDS_HUMAN')),
  attempt_no integer not null default 0 check (attempt_no >= 0),
  timeout_seconds integer not null default 300 check (timeout_seconds between 10 and 1800),
  input_drive_file_id text,
  input_original_filename text,
  input_working_name text not null default 'input.blend',
  input_size bigint,
  input_sha256 text,
  output_refs jsonb not null default '{}'::jsonb,
  output_sha256 text,
  versions jsonb not null default '{}'::jsonb,
  lease_owner text,
  lease_until timestamptz,
  error_code text,
  error_detail jsonb not null default '{}'::jsonb,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ukie_bridge_job_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.ukie_bridge_jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  stage text,
  status text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ukie_bridge_artifacts (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.ukie_bridge_jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  artifact_role text not null,
  file_name text not null,
  original_filename text,
  mime_type text,
  byte_size bigint check (byte_size is null or byte_size >= 0),
  sha256 text,
  drive_file_id text,
  drive_url text,
  verification_status text not null default 'LOCAL_SAVED' check (verification_status in ('LOCAL_SAVED','HASHED','UPLOADING','UPLOADED','READBACK_VERIFYING','VERIFIED','FAILED')),
  verified_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(job_id, artifact_role, file_name)
);

-- Production rule: enable RLS and grant only the operations the authenticated owner needs.
-- See deployed database policies for the authoritative policy definitions.
