-- UKIE AI Virtual Browser dedicated Supabase migration.
-- DO NOT apply this to the legacy JONYCON project.
-- The vault intentionally has RLS enabled with no client policies: only the
-- service-role Edge Function may read/write encrypted token material.

create table if not exists public.ukie_provider_token_vault (
  user_id uuid not null,
  provider text not null,
  token_kind text not null check (token_kind in ('refresh', 'access')),
  ciphertext text not null,
  iv text not null,
  key_version text not null default 'v1',
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, provider, token_kind)
);

alter table public.ukie_provider_token_vault enable row level security;

-- Intentionally NO SELECT/INSERT/UPDATE/DELETE policies for anon/authenticated.
-- Supabase service_role bypasses RLS and is used only inside verified Edge Functions.

create table if not exists public.ukie_auth_refresh_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  provider text not null,
  event_type text not null,
  status text not null,
  error_code text,
  token_expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.ukie_auth_refresh_events enable row level security;

create index if not exists ukie_auth_refresh_events_user_provider_created_idx
  on public.ukie_auth_refresh_events(user_id, provider, created_at desc);

comment on table public.ukie_provider_token_vault is
  'Service-only AES-GCM ciphertext for provider credentials. Never expose through Base44/Drive/client queries.';
comment on table public.ukie_auth_refresh_events is
  'Service-only refresh audit metadata. Must never contain raw provider tokens or client secrets.';
